// A curated list of color names and their hex values.
// Sourced from common color name standards.

export const colorNameList: { name: string; hex: string }[] = [
    { name: "Black", hex: "#000000" },
    { name: "Navy", hex: "#000080" },
    { name: "Dark Blue", hex: "#00008B" },
    { name: "Medium Blue", hex: "#0000CD" },
    { name: "Blue", hex: "#0000FF" },
    { name: "Dark Green", hex: "#006400" },
    { name: "Green", hex: "#008000" },
    { name: "Teal", hex: "#008080" },
    { name: "Dark Cyan", hex: "#008B8B" },
    { name: "Deep Sky Blue", hex: "#00BFFF" },
    { name: "Dark Turquoise", hex: "#00CED1" },
    { name: "Medium Spring Green", hex: "#00FA9A" },
    { name: "Lime", hex: "#00FF00" },
    { name: "Spring Green", hex: "#00FF7F" },
    { name: "Aqua", hex: "#00FFFF" },
    { name: "Cyan", hex: "#00FFFF" },
    { name: "Midnight Blue", hex: "#191970" },
    { name: "Dodger Blue", hex: "#1E90FF" },
    { name: "Light Sea Green", hex: "#20B2AA" },
    { name: "Forest Green", hex: "#228B22" },
    { name: "Sea Green", hex: "#2E8B57" },
    { name: "Dark Slate Gray", hex: "#2F4F4F" },
    { name: "Lime Green", hex: "#32CD32" },
    { name: "Medium Sea Green", hex: "#3CB371" },
    { name: "Turquoise", hex: "#40E0D0" },
    { name: "Royal Blue", hex: "#4169E1" },
    { name: "Steel Blue", hex: "#4682B4" },
    { name: "Dark Slate Blue", hex: "#483D8B" },
    { name: "Medium Turquoise", hex: "#48D1CC" },
    { name: "Indigo", hex: "#4B0082" },
    { name: "Dark Olive Green", hex: "#556B2F" },
    { name: "Cadet Blue", hex: "#5F9EA0" },
    { name: "Cornflower Blue", hex: "#6495ED" },
    { name: "Slate Blue", hex: "#6A5ACD" },
    { name: "Olive Drab", hex: "#6B8E23" },
    { name: "Medium Slate Blue", hex: "#7B68EE" },
    { name: "Lawn Green", hex: "#7CFC00" },
    { name: "Chartreuse", hex: "#7FFF00" },
    { name: "Aquamarine", hex: "#7FFFD4" },
    { name: "Maroon", hex: "#800000" },
    { name: "Purple", hex: "#800080" },
    { name: "Olive", hex: "#808000" },
    { name: "Gray", hex: "#808080" },
    { name: "Sky Blue", hex: "#87CEEB" },
    { name: "Light Sky Blue", hex: "#87CEFA" },
    { name: "Blue Violet", hex: "#8A2BE2" },
    { name: "Dark Red", hex: "#8B0000" },
    { name: "Dark Magenta", hex: "#8B008B" },
    { name: "Saddle Brown", hex: "#8B4513" },
    { name: "Dark Sea Green", hex: "#8FBC8F" },
    { name: "Light Green", hex: "#90EE90" },
    { name: "Medium Purple", hex: "#9370DB" },
    { name: "Dark Violet", hex: "#9400D3" },
    { name: "Pale Green", hex: "#98FB98" },
    { name: "Dark Orchid", hex: "#9932CC" },
    { name: "Yellow Green", hex: "#9ACD32" },
    { name: "Sienna", hex: "#A0522D" },
    { name: "Brown", hex: "#A52A2A" },
    { name: "Dark Gray", hex: "#A9A9A9" },
    { name: "Light Blue", hex: "#ADD8E6" },
    { name: "Green Yellow", hex: "#ADFF2F" },
    { name: "Pale Turquoise", hex: "#AFEEEE" },
    { name: "Light Steel Blue", hex: "#B0C4DE" },
    { name: "Powder Blue", hex: "#B0E0E6" },
    { name: "Firebrick", hex: "#B22222" },
    { name: "Dark Goldenrod", hex: "#B8860B" },
    { name: "Medium Orchid", hex: "#BA55D3" },
    { name: "Rosy Brown", hex: "#BC8F8F" },
    { name: "Dark Khaki", hex: "#BDB76B" },
    { name: "Silver", hex: "#C0C0C0" },
    { name: "Medium Violet Red", hex: "#C71585" },
    { name: "Indian Red", hex: "#CD5C5C" },
    { name: "Peru", hex: "#CD853F" },
    { name: "Chocolate", hex: "#D2691E" },
    { name: "Tan", hex: "#D2B48C" },
    { name: "Light Gray", hex: "#D3D3D3" },
    { name: "Thistle", hex: "#D8BFD8" },
    { name: "Orchid", hex: "#DA70D6" },
    { name: "Goldenrod", hex: "#DAA520" },
    { name: "Pale Violet Red", hex: "#DB7093" },
    { name: "Crimson", hex: "#DC143C" },
    { name: "Gainsboro", hex: "#DCDCDC" },
    { name: "Plum", hex: "#DDA0DD" },
    { name: "Burlywood", hex: "#DEB887" },
    { name: "Light Cyan", hex: "#E0FFFF" },
    { name: "Lavender", hex: "#E6E6FA" },
    { name: "Dark Salmon", hex: "#E9967A" },
    { name: "Violet", hex: "#EE82EE" },
    { name: "Pale Goldenrod", hex: "#EEE8AA" },
    { name: "Light Coral", hex: "#F08080" },
    { name: "Khaki", hex: "#F0E68C" },
    { name: "Alice Blue", hex: "#F0F8FF" },
    { name: "Honeydew", hex: "#F0FFF0" },
    { name: "Azure", hex: "#F0FFFF" },
    { name: "Sandy Brown", hex: "#F4A460" },
    { name: "Wheat", hex: "#F5DEB3" },
    { name: "Beige", hex: "#F5F5DC" },
    { name: "White Smoke", hex: "#F5F5F5" },
    { name: "Mint Cream", hex: "#F5FFFA" },
    { name: "Ghost White", hex: "#F8F8FF" },
    { name: "Salmon", hex: "#FA8072" },
    { name: "Antique White", hex: "#FAEBD7" },
    { name: "Linen", hex: "#FAF0E6" },
    { name: "Light Goldenrod Yellow", hex: "#FAFAD2" },
    { name: "Old Lace", hex: "#FDF5E6" },
    { name: "Red", hex: "#FF0000" },
    { name: "Fuchsia", hex: "#FF00FF" },
    { name: "Magenta", hex: "#FF00FF" },
    { name: "Deep Pink", hex: "#FF1493" },
    { name: "Orange Red", hex: "#FF4500" },
    { name: "Tomato", hex: "#FF6347" },
    { name: "Hot Pink", hex: "#FF69B4" },
    { name: "Coral", hex: "#FF7F50" },
    { name: "Dark Orange", hex: "#FF8C00" },
    { name: "Light Salmon", hex: "#FFA07A" },
    { name: "Orange", hex: "#FFA500" },
    { name: "Light Pink", hex: "#FFB6C1" },
    { name: "Pink", hex: "#FFC0CB" },
    { name: "Gold", hex: "#FFD700" },
    { name: "Peach Puff", hex: "#FFDAB9" },
    { name: "Navajo White", hex: "#FFDEAD" },
    { name: "Moccasin", hex: "#FFE4B5" },
    { name: "Bisque", hex: "#FFE4C4" },
    { name: "Misty Rose", hex: "#FFE4E1" },
    { name: "Blanched Almond", hex: "#FFEBCD" },
    { name: "Papaya Whip", hex: "#FFEFD5" },
    { name: "Lavender Blush", hex: "#FFF0F5" },
    { name: "Seashell", hex: "#FFF5EE" },
    { name: "Cornsilk", hex: "#FFF8DC" },
    { name: "Lemon Chiffon", hex: "#FFFACD" },
    { name: "Floral White", hex: "#FFFAF0" },
    { name: "Snow", hex: "#FFFAFA" },
    { name: "Yellow", hex: "#FFFF00" },
    { name: "Light Yellow", hex: "#FFFFE0" },
    { name: "Ivory", hex: "#FFFFF0" },
    { name: "White", hex: "#FFFFFF" },
];
